#server:
#  port: 30000
#
#logging:
#  level:
#    com.atguigu.gulimall: debug
#
#gulimall:
#  oauth2:
#    weibo:
#      client-id: 813131548
#      client-secret: f461989f2f7ee32f0b2da625bbe5a872
#      grant-type: authorization_code
#      redirect-uri: http://auth.gulimall.com/oauth2/weibo/getAccessToken
#      weibo-uri: https://api.weibo.com
#
#spring:
#  application:
#    name: gulimall-third-paryt
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.56.10:8848
#        username: nacos
#        password: nacos
#        namespace: 12a22b95-014c-4d8f-a19a-2a4cc74d80b3
#        group: gulimall
#        service: ${spring.application.name}
#
#    alicloud:
#      access-key: LTAI4Fnx87yV1CaSmPmniDp1
#      secret-key: 5uqsJ5wio6ctJH4vu7tkx5xRktPyBV
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
#        bucket: study-chengcheng
#
#      sms:
#        host: https://smsmsgs.market.alicloudapi.com
#        path: /sms/
#        sign: 175622
#        skin: 1
#        appkey: 203841681
#        appsecret: u5LARn2E6q6CkEh6MrsSGZhhjKFkNwEA
#        appcode: 22bdb919b2be4c6d897a3b3509ed4c68
