#server:
#  port: 20000
#
#redisson:
#  single-server-config:
#    address: 192.168.56.10:6379
#
#spring:
#  application:
#    name: gulimall-auth-server
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.56.10:8848
#        username: nacos
#        password: nacos
#        namespace: 12a22b95-014c-4d8f-a19a-2a4cc74d80b3
#        group: gulimall
#        service: ${spring.application.name}
