#server:
#  port: 25000
#
#logging:
#  level:
#    com.atguigu.gulimall: debug
#
#redisson:
#  single-server-config:
#    address: 192.168.56.10:6379
#
#spring:
#  application:
#    name: gulimall-seckill
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.56.10:8848
#        username: nacos
#        password: nacos
#        namespace: 12a22b95-014c-4d8f-a19a-2a4cc74d80b3
#        group: gulimall
#        service: ${spring.application.name}
#
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#
#  task:
#    execution:
#      pool:
#        core-size: 20
#        max-size: 50
#
#  rabbitmq:
#    host: 192.168.56.10
#    port: 5672
#    virtual-host: /
#    publisher-confirm-type: correlated
#    publisher-returns: true
#    template:
#      mandatory: true
#    listener:
#      direct:
#        acknowledge-mode: manual
#
#  zipkin:
#    base-url: http://192.168.56.10:9411/
#    discovery-client-enabled: false
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1
