#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.56.10:8848
#  application:
#    name: gulimall-order
#  rabbitmq:
#    host: 192.168.56.10
#    port: 5672
#    virtual-host: /
#    publisher-confirm-type: correlated
#    publisher-returns: true
#    template:
#      mandatory: true
#    listener:
#      direct:
#        acknowledge-mode: manual
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 9000
#
#seata:
#  enabled: true
#  application-id: gulimall-order
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 192.168.56.10:8848
#  config:
#    type: file
#    file:
#      name: file.conf
#  client:
#    support:
#      spring:
#        datasource-autoproxy: true
