#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.56.10:8848
#  application:
#    name: gulimall-search
#  elasticsearch:
#    rest:
#      uris: http://192.168.56.10:9200
#
#server:
#  port: 31000
#
#logging:
#  level:
#    com.atguigu.gulimall: debug
